export const dummyData = [
  { 
    id:'01',
    trackingId: 'ABC123',
    status:'Shipment Delivered',
    events: [
      
      {
        id: 1,
        date: 'NOV 28 2023',
        time: '09.27 AM',
        status: 'Delivered',
        location: 'SOUTH BEND IN US',
      },
      {
        id: 2,
        date: 'NOV 28 2023',
        time: '08.56 AM',
        status: 'Out For Delivery Today',
        location: 'SOUTH BEND IN US',
      },
      {
        id: 3,
        date: 'NOV 28 2023',
        time: '06.53 AM',
        status: 'Processing at UPS Facility',
        location: 'SOUTH BEND IN US',
      },
      {
        id: 4,
        date: 'NOV 27 2023',
        time: '10.54 AM',
        status: 'Arrived at Facility',
        location: 'SOUTH BEND IN US',
      },
      {
        id: 5,
        date: 'NOV 27 2023',
        time: '09.27 AM',
        status: 'Departed from Facility',
        location: 'Plainfield IN US',
      },
      {
        id: 6,
        date: 'NOV 27 2023',
        time: '09.27 AM',
        status: 'Arrived at Facility',
        location: 'Plainfield IN US',
      },
      {
        id: 7,
        date: 'NOV 27 2023',
        time: '08.27 AM',
        status: 'Departed from Facility',
        location: 'Plainfield IN US',
      },
      {
        id: 8,
        date: 'NOV 27 2023',
        time: '09.27 AM',
        status: 'Arrived at Facility',
        location: 'Plainfield IN US',
      },
    ],
  },
  {
    id:"02",
    trackingId: 'XYZ123',
    status:'Shipment Delivered',
    events: [
      {
        id: 1,
        date: 'NOV 17 2023',
        time: '09.27 AM',
        status: 'Delivered',
        location: 'Bengaluru,KA',
      },
      {
        id: 2,
        date: 'NOV 13 2023',
        time: '08.56 AM',
        status: 'Out For Delivery Today',
        location: 'Bengaluru,KA',
      },
      {
        id: 3,
        date: 'NOV 13 2023',
        time: '06.53 AM',
        status: 'Processing at UPS Facility',
        location: 'Bengaluru,KA',
      },
      {
        id: 4,
        date: 'NOV 12 2023',
        time: '10.54 AM',
        status: 'Arrived at Facility',
        location: 'Bengaluru,KA',
      },
      {
        id: 5,
        date: 'NOV 12 2023',
        time: '09.27 AM',
        status: 'Departed from Facility',
        location: 'Hosur,TN',
      },
      {
        id: 6,
        date: 'NOV 12 2023',
        time: '09.27 AM',
        status: 'Arrived at Facility',
        location: 'Hosur,TN',
      },
      {
        id: 7,
        date: 'NOV 12 2023',
        time: '08.27 AM',
        status: 'Departed from Facility',
        location: 'Chennai ,TN',
      },
      {
        id: 8,
        date: 'NOV 12 2023',
        time: '09.27 AM',
        status: 'Arrived at Facility',
        location: 'Chennai , TN',
      },
    ],
  },
  { 
    id:'03',
    trackingId: 'efx200',
    status:'Shipment Delivered',
    events: [
      
      {
        id: 1,
        date: 'NOV 09 2023',
        time: '09.27 AM',
        status: 'Delivered',
        location: 'Hyderabad IN',
      },
      {
        id: 2,
        date: 'NOV 09 2023',
        time: '08.56 AM',
        status: 'Out For Delivery Today',
        location: 'Hyderabad IN',
      },
      {
        id: 3,
        date: 'NOV 09 2023',
        time: '06.53 AM',
        status: 'Processing at UPS Facility',
        location: 'Hyderabad IN',
      },
      {
        id: 4,
        date: 'NOV 08 2023',
        time: '10.54 AM',
        status: 'Arrived at Facility',
        location: 'Hyderabad IN',
      },
      {
        id: 5,
        date: 'NOV 09 2023',
        time: '09.27 AM',
        status: 'Departed from Facility',
        location: 'Bangalore IN',
      },
      {
        id: 6,
        date: 'NOV 08 2023',
        time: '09.27 AM',
        status: 'Arrived at Facility',
        location: 'Bangalore IN',
      },
      {
        id: 7,
        date: 'NOV 08 2023',
        time: '08.27 AM',
        status: 'Departed from Facility',
        location: 'Bangalore IN',
      },
      {
        id: 8,
        date: 'NOV 08 2023',
        time: '09.27 AM',
        status: 'Arrived at Facility',
        location: 'Bangalore IN',
      },
    ],
  },
];
